name: sigepweb
description: Utilize serviços dos Correios no seu App como buscar CEP ou calcular preços e prazos de encomendas
version: 1.0.0
repository: https://github.com/marcobraghim/sigepweb
issue_tracker: https://github.com/marcobraghim/sigepweb/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  xml2json: ^4.2.0
  dio: ^3.0.9
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_coverage_badge: ^0.0.1+1
